jgolla/torn-api

lib/Interfaces.ts, lib/User.ts
=> fix: updates for patch 185

lib/Faction.ts, lib/Interfaces.ts, lib/Torn.ts, lib/User.ts
=> fix: update for patch 188

lib/Interfaces.ts
=> fix: update for patch 189

lib/Interfaces.ts, lib/Torn.ts, lib/User.ts
=> fix: update for patch 191

lib/Faction.ts, lib/Interfaces.ts
=> fix: update for patch 192

lib/Interfaces.ts, lib/User.ts
=> fix: update for patch 193

lib/Interfaces.ts, lib/Torn.ts, package-lock.json
=> fix: update for patch 195

lib/Interfaces.ts, package-lock.json
=> fix: update for patch 201

.github/workflows/main.yml, lib/Company.ts, lib/Interfaces.ts, lib/TornAPIBase.ts, lib/User.ts
=> fix: update for patch 204

.eslintrc, lib/Faction.ts, lib/TornAPIBase.ts, lib/User.ts
=> chore(lint): update lint rules

lib/Faction.ts, lib/Interfaces.ts
=> fix(faction): clean up interface use

lib/Interfaces.ts, lib/Torn.ts, test/Torn.test.ts, test/utils/tests.json
=> fix: update for patch 207

lib/Faction.ts, lib/Interfaces.ts, package-lock.json, test/Faction.test.ts, test/utils/tests.json
=> fix: updates for patch 227

lib/Interfaces.ts, test/utils/tests.json
=> fix: updates for patch 229

lib/Interfaces.ts, package-lock.json
=> fix: updates for patch 234

lib/Interfaces.ts, test/Faction.test.ts, test/utils/tests.json
=> fix(faction): add status to applications

lib/index.ts
=> fix: no response from server on error

lib/Company.ts, lib/Faction.ts, lib/ItemMarket.ts, lib/Property.ts, lib/Torn.ts, lib/TornAPIBase.ts, lib/User.ts, lib/index.ts
I'll handle tests in the morning.
=> feat: add comment to each request

lib/Interfaces.ts, lib/Torn.ts, test/Torn.test.ts, test/utils/tests.json
=> fix: updates for patch 280

lib/Interfaces.ts, lib/User.ts, test/User.test.ts, test/utils/tests.json
Updates for user events.
https://www.torn.com/forums.php#/p=threads&f=63&t=16146310&b=0&a=0&start=0&to=23394041
=> fix: updates for user events

lib/Company.ts, test/Company.test.ts
=> fix: remove company newsfull

lib/Interfaces.ts, lib/User.ts, package-lock.json
https://www.torn.com/forums.php#/p=threads&f=1&t=16363114&b=0&a=0
- [API] Closed the users -> inventory selection until the back-end can be rebuilt
=> fix: updates for patch 313

lib/TornAPIBase.ts, lib/User.ts, test/User.test.ts, test/utils/tests.json
=> fix: issue with api query

.github/workflows/main.yml
=> build: update github actions

lib/Interfaces.ts, lib/Key.ts, lib/TornAPIBase.ts, lib/TornOpenAPI.ts, test/Key.test.ts, test/utils/tests.json
Updating key to use new V2 endpoints.
=> feat(key): update key to v2 api
